// Generated by `node scripts/frames.mjs`. Do not edit by hand.
//
// Each quad is the screen's four corners in the artwork's own pixels, ordered
// top-left, top-right, bottom-right, bottom-left.
import type { FrameQuad } from "./frameTypes";

export const FRAME_QUADS: Record<string, FrameQuad> = {
  "monitor-angled.png": {
    width: 1417,
    height: 1110,
    quad: [[244.1, 55], [1094.2, 315.9], [1176.7, 859.2], [307.3, 629.8]],
  },
  "monitor-desk.png": {
    width: 1448,
    height: 1086,
    quad: [[353.9, 251], [1100.1, 251], [1104.4, 663], [348.7, 663]],
  },
  "monitor-shelf.png": {
    width: 1448,
    height: 1086,
    quad: [[386, 328], [1061, 328], [1061, 702], [386, 702]],
  },
  "phone-held-out.png": {
    width: 1448,
    height: 1086,
    quad: [[194.6, 295.8], [532.7, 139.8], [869.3, 826.7], [543.7, 978.7]],
  },
  "phone-in-hand.png": {
    width: 1122,
    height: 1402,
    quad: [[426.5, 133.3], [715.8, 137.9], [624.9, 887.2], [330.8, 849.7]],
  },
  "tablet-held.png": {
    width: 1086,
    height: 1448,
    quad: [[158, 354.3], [955.5, 320], [1035.9, 864.4], [217.7, 928.6]],
  },
};
